[ImageContainer]
Hidden=1
[Image]
Hidden=1

[Title.2_42]
Meter=String
Text="Change log v2.42"
MeterStyle=Sec.String:S | Style.Title:S

[Description.2_42.0]
Meter=String
Text="- Fixed media controls on all variants"
MeterStyle=Sec.String:S | Style.Description:S

[Title.2_41]
Meter=String
Text="Change log v2.41"
Y=(#Sec.P#)R
MeterStyle=Sec.String:S | Style.Title:S

[Description.2_41.0]
Meter=String
Text="- Blur variant with rounded corners#CRLF#- Scrolling text in 'side' variant#CRLF#- Fixed big circ progress bar"
MeterStyle=Sec.String:S | Style.Description:S